### ISSUE TITLE
the server crashed when swiftly loaded

### ISSUE THREAD

**Issue by 2vg** [swiftly-solution/swiftly#45]
OS: Linux, Docker(use image from [joedwards32/CS2](https://github.com/joedwards32/CS2) and patched with `libreadline8`)
Used plugin: nothing

The server seems to be crashing trying to load Swiftly, even though Swiftly is failing to load.
```
cs2-dedicated  | [Swiftly] [Patch] Patches performed: 00.
cs2-dedicated  | [Swiftly] [Database] 2 databases have been succesfully loaded.
cs2-dedicated  | [Swiftly] [Addons] Loaded 0 addons.
cs2-dedicated  | [Swiftly] [Hooks] Hooking PrecacheResource...
cs2-dedicated  | [Swiftly] [Hooks] Hooked PrecacheResource.
cs2-dedicated  | [Swiftly] [Hooks] Hooking CCSPlayer_MovementServices_CheckJumpPre...
cs2-dedicated  | [Swiftly] [Hooks] Hooked CCSPlayer_MovementServices_CheckJumpPre.
cs2-dedicated  | [Swiftly] [Hooks] Hooking CLoggingSystem_LogDirect...
cs2-dedicated  | [Swiftly] [Hooks] Hooked CLoggingSystem_LogDirect.
cs2-dedicated  | [Swiftly] [Hooks] Hooking FireOutputInternal...
cs2-dedicated  | [Swiftly] [FuncHook] Failed create for FireOutputInternal.
cs2-dedicated  | Error Message: Signature was not found.
cs2-dedicated  | [Swiftly] [Load] Hooks failed to initialize.
cs2-dedicated  | [META] Failed to load plugin addons/swiftly/bin/linuxsteamrt64/swiftly: 
...
cs2-dedicated  | [Swiftly] [Crash Reporter] A crash has occured and a dump has been created:
...
```

**Comment by skuzzis** [comment]
Hi there,

If you look closely, this is the error: `Signature was not found.`

Update the bin and gamedata folders.

**Comment by skuzzis** [comment]
It already is the same.

Just that, in your gamedata folder uploaded for your server, the FireOutputInternal is not being set in `signatures.json`.

**Comment by 2vg** [comment]
It's in my `signatures.json` too 🥹
![image](https://github.com/user-attachments/assets/2752d91e-73d2-4134-9468-af1aab076a2f)

**Comment by skuzzis** [comment]
Then, the only thing I can think of is that the docker image isn't at its last version.

Try to update it with `docker pull`.

**Comment by 2vg** [comment]
@skuzzis uhhhh sorry, I just checked all my files, the cause is `CSSharp` is enabled.
I started setting up a server a few days ago and didn't know that `CSSharp` and `Swiftly` can't coexist.
It's very attractive to be able to quickly develop simple plugins with Lua scripts, but some Fix plugins only exist in C#, so I would like to disable them for the time being.
Thank you for your support! !

**Comment by skuzzis** [comment]
Don't worry, we're glad that you've found the issue. Don't hesitate to contact us again in case there are other problems.
