### ISSUE TITLE
Tried to add a hook with invalid memory.

### ISSUE THREAD

**Issue by iamtwist** [swiftly-solution/swiftly#64]
[Swiftly] [AddHook] ERROR: Tried to add a hook with invalid memory.
[Swiftly] [plugin:weapon_restrictor] Error: Invalid hook data passed to AddPreHookListener.
[Swiftly] [Plugin Reload] Plugin 'weapon_restrictor' has been reloaded.

**Comment by skuzzis** [comment]
Try with version [v1.3.47](https://github.com/swiftly-solution/swiftly/releases/tag/v1.3.47).

**Comment by iamtwist** [comment]
solved
