### ISSUE TITLE
My server randomly crashed.

### ISSUE THREAD

**Issue by iamtwist** [swiftly-solution/swiftly#65]
================================
Command: /home/container/game/bin/linuxsteamrt64/cs2 -dedicated -ip 45.13.151.105 -port 27015 +map de_mirage -maxplayers 32 +mapgroup mg_active +game_type 0 +game_mode 1 +sv_setsteamaccount REDACTED +host_workshop_map +host_workshop_collection
Map: de_mirage
================================

00. 0x7f927e9d4adf signal_handler(int) + 319
01. 0x7f92d028ed60 /lib/x86_64-linux-gnu/libc.so.6(+0x38d60) [0x7f92d028ed60]
02. 0x7f927eaa26d4 SDKBaseClass::AccessSDKLua(std::string, unsigned long, lua_State*) + 9700
03. 0x7f927eaa5813 SDKBaseClass::GetProp(lua_State*) + 931
04. 0x7f927ebb485f /home/container/game/csgo/addons/swiftly/bin/linuxsteamrt64/swiftly.so(+0x68285f) [0x7f927ebb485f]
05. 0x7f927ebd52fd /home/container/game/csgo/addons/swiftly/bin/linuxsteamrt64/swiftly.so(+0x6a32fd) [0x7f927ebd52fd]
06. 0x7f927ebcfb77 /home/container/game/csgo/addons/swiftly/bin/linuxsteamrt64/swiftly.so(+0x69db77) [0x7f927ebcfb77]
07. 0x7f927ebb4ebb /home/container/game/csgo/addons/swiftly/bin/linuxsteamrt64/swiftly.so(+0x682ebb) [0x7f927ebb4ebb]
08. 0x7f927ebb2b70 /home/container/game/csgo/addons/swiftly/bin/linuxsteamrt64/swiftly.so(+0x680b70) [0x7f927ebb2b70]
09. 0x7f927ebb55d3 /home/container/game/csgo/addons/swiftly/bin/linuxsteamrt64/swiftly.so(+0x6835d3) [0x7f927ebb55d3]
10. 0x7f927ebcc2ec lua_pcallk + 124
11. 0x7f927ea17a38 LuaPlugin::PluginTriggerEvent(std::string, std::string, std::string, PluginEvent*) + 376
12. 0x7f927ea0b166 Plugin::TriggerEvent(std::string, std::string, std::string, PluginEvent*) + 134
13. 0x7f927ea0d51b PluginManager::ExecuteEvent(std::string, std::string, std::string, PluginEvent*) + 219
14. 0x7f927e98572d EventManager::OnFireEvent(IGameEvent*, bool) + 685
15. 0x7f927e987427 __SourceHook_FHCls_IGameEventManager2FireEvent0::Func(IGameEvent*, bool) + 183
16. 0x7f928610118a /home/container/game/bin/linuxsteamrt64/../../csgo/bin/linuxsteamrt64/libserver.so(+0xbb318a) [0x7f928610118a]

without any more infos if is about a plugin or something. Maybe it's something from framework, if u have any idea

**Comment by blu133721** [comment]
Open a support thread in the discord server.
